{
  "formatVersion": "1.1",
  "component": {
    "group": "garbage",
    "module": "int-fmt",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-fmt-0.3.0.aar",
          "url": "int-fmt-0.3.0.aar",
          "size": 26396,
          "sha512": "f557fdc0b99e44355139d9ac3fdaac47aa54c92036e141d4e65f3fe76094bb89928d23647a559d134faf565d4af8c5b8f79014e439cc18eea010ed243fdb77c1",
          "sha256": "be18f85912995db1d0980766ecb15d15648c3d593821371cd58f34a1bb4cd24f",
          "sha1": "c228f3a38a3906f9d3316129e14da818a769387c",
          "md5": "e68043e8ce6d59d4492536ff2f68ca84"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-fmt-0.3.0.aar",
          "url": "int-fmt-0.3.0.aar",
          "size": 26396,
          "sha512": "f557fdc0b99e44355139d9ac3fdaac47aa54c92036e141d4e65f3fe76094bb89928d23647a559d134faf565d4af8c5b8f79014e439cc18eea010ed243fdb77c1",
          "sha256": "be18f85912995db1d0980766ecb15d15648c3d593821371cd58f34a1bb4cd24f",
          "sha1": "c228f3a38a3906f9d3316129e14da818a769387c",
          "md5": "e68043e8ce6d59d4492536ff2f68ca84"
        }
      ]
    }
  ]
}
