{
  "formatVersion": "1.1",
  "component": {
    "group": "garbage",
    "module": "tls",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20-Beta"
          }
        }
      ],
      "files": [
        {
          "name": "tls-0.1.0.jar",
          "url": "tls-0.1.0.jar",
          "size": 16793,
          "sha512": "21b43439c31172663af627f52d24fce1a3400a8e86f46cc7dc23efd3e56cc0a327330532352cd87f0141928f113021e98cc4e8fa71902c9783d10bb242ad0ad6",
          "sha256": "2a7ede984413879f6d2e57510ca3b7c0d8ca3f9117fad24cbaea20613ebd663c",
          "sha1": "e90a81889e91d15e9a9774fcfea0ac4b2b11058c",
          "md5": "bab35c846473cc4f19e1555e6b7db50c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20-Beta"
          }
        }
      ],
      "files": [
        {
          "name": "tls-0.1.0.jar",
          "url": "tls-0.1.0.jar",
          "size": 16793,
          "sha512": "21b43439c31172663af627f52d24fce1a3400a8e86f46cc7dc23efd3e56cc0a327330532352cd87f0141928f113021e98cc4e8fa71902c9783d10bb242ad0ad6",
          "sha256": "2a7ede984413879f6d2e57510ca3b7c0d8ca3f9117fad24cbaea20613ebd663c",
          "sha1": "e90a81889e91d15e9a9774fcfea0ac4b2b11058c",
          "md5": "bab35c846473cc4f19e1555e6b7db50c"
        }
      ]
    }
  ]
}
