{
  "formatVersion": "1.1",
  "component": {
    "group": "garbage",
    "module": "int-fmt",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "int-fmt-0.2.3.aar",
          "url": "int-fmt-0.2.3.aar",
          "size": 13287,
          "sha512": "3cb49b3361e2ed6132b2eaf8ae3a72c3bbe95b6856ee0f52eedc15badda35b23ac498898bdf4f0707d70849829f78addc6c3aa79534106079e11e24607c2cbdf",
          "sha256": "9741fa03dfb234fd8df1b57c289c540638fbe92c5ff12236f3a1397b08b48b20",
          "sha1": "16a0d7c99e9be757910e179f78cfc1ce6ea9f5e5",
          "md5": "af59305b72af3ca0e117e89afce35ced"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "int-fmt-0.2.3.aar",
          "url": "int-fmt-0.2.3.aar",
          "size": 13287,
          "sha512": "3cb49b3361e2ed6132b2eaf8ae3a72c3bbe95b6856ee0f52eedc15badda35b23ac498898bdf4f0707d70849829f78addc6c3aa79534106079e11e24607c2cbdf",
          "sha256": "9741fa03dfb234fd8df1b57c289c540638fbe92c5ff12236f3a1397b08b48b20",
          "sha1": "16a0d7c99e9be757910e179f78cfc1ce6ea9f5e5",
          "md5": "af59305b72af3ca0e117e89afce35ced"
        }
      ]
    }
  ]
}
