{
  "formatVersion": "1.1",
  "component": {
    "group": "garbage",
    "module": "int-fmt",
    "version": "0.2.1+garbage-int-fmt",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "int-fmt-0.2.1+garbage-int-fmt.aar",
          "url": "int-fmt-0.2.1+garbage-int-fmt.aar",
          "size": 13208,
          "sha512": "4f50e3667965dc6f1842f5155bcac94d5b939b1df5efced838cd17169d09956ff16b5d5b3ac7735744e63b1f238232ab0a477502ca845f1ad1a3ae219fc4ee81",
          "sha256": "7bdfd85fd3a7199b552f6e72493782cbeba0fe224de8604cc0c3cdb01e681946",
          "sha1": "d332785ddd27cd3d51688135164f9579bc23516b",
          "md5": "53a794e553f587bcd430889b51d1b7c7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "int-fmt-0.2.1+garbage-int-fmt.aar",
          "url": "int-fmt-0.2.1+garbage-int-fmt.aar",
          "size": 13208,
          "sha512": "4f50e3667965dc6f1842f5155bcac94d5b939b1df5efced838cd17169d09956ff16b5d5b3ac7735744e63b1f238232ab0a477502ca845f1ad1a3ae219fc4ee81",
          "sha256": "7bdfd85fd3a7199b552f6e72493782cbeba0fe224de8604cc0c3cdb01e681946",
          "sha1": "d332785ddd27cd3d51688135164f9579bc23516b",
          "md5": "53a794e553f587bcd430889b51d1b7c7"
        }
      ]
    }
  ]
}
